name: Update Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy newest 
        run: |
          git config --global user.email "chris@casualcompany.de"
          git config --global user.name "ProdIsMyDev"
          cd docs
          git init
          git add .
          git commit -m "updating documentation"
          git remote add origin https://ProdIsMyDev:${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}@github.com/[ORGANISATION]/[REPO].git
          git push origin master -f
          
